- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks: 
    - name: Update apt
      command: apt-get update
      become_user: root
      
    - name: Install Docker
      command: apt-get install -y docker.io
      become: yes
      become_user: root

    - name: Start Docker service
      command: systemctl start docker
      become: yes
      become_user: root

    - name: Add testadmin to Docker group
      command: usermod -aG docker testadmin
      become: yes
      become_user: root

    - name: Deploy Docker container
      command: docker run -itd -p 8089:8082 gopallpatell/medicure:v1.0
      become: yes
      become_user: root
